# Generated by Django 5.0.6 on 2024-07-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Restaurant',
            new_name='restaurant',
        ),
    ]
