# Generated by Django 5.0.6 on 2024-07-05 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.AddField(
            model_name='photo',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.review'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
