# Generated by Django 5.0.6 on 2024-07-04 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='review',
        ),
        migrations.AddField(
            model_name='photo',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.restaurant'),
            preserve_default=False,
        ),
    ]
