# Generated by Django 5.0.6 on 2024-07-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_restaurant_address_restaurant_rating_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='place_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
